Revised README to be more formal
fosskers/vectortiles pull request #18
Opened 2018-11-11 21:02 UTC by sidagrawal

2018-11-14 01:16 UTC, fosskers requested changes

2018-11-14 01:16 UTC, fosskers commented on README.md
> +Invented by [Mapbox](https://www.mapbox.com/), `vectortiles` are a combination
```suggestion
Invented by [Mapbox](https://www.mapbox.com/), VectorTiles are a combination
```

2018-11-14 01:16 UTC, fosskers commented on README.md
> +checks while decoding depends on willingness to sacrifice performance.
```suggestion
checking that occurs while decoding depends on willingness to sacrifice performance.
```

2018-11-16 23:26 UTC, sidagrawal commented on README.md
> +Invented by [Mapbox](https://www.mapbox.com/), `vectortiles` are a combination
Made the change

2018-11-16 23:26 UTC, sidagrawal commented on README.md
> +checks while decoding depends on willingness to sacrifice performance.
Made the change

2018-11-17 05:23 UTC, fosskers approved these changes

2018-11-17 05:23 UTC, merged